#!/usr/bin/env node
// Build-time: encrypt ATN_TOKEN with ATN_PASSWORD into src/lib/encrypted-token.ts.
// Missing env vars -> emit empty fields (dev fallback: gate stays bypassed,
// the existing API-key dialog handles manual entry).

import { webcrypto } from "node:crypto"
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { parseEnv } from "node:util"

const ITER = 200_000
const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(HERE, "../src/lib/encrypted-token.ts")

// ATN_TOKEN / ATN_PASSWORD may come from the environment or from the repo-root
// .devcontainer-exclude/.env file (git-ignored, devcontainer-mounted). Real
// environment variables win over file values.
const ENV_FILE = resolve(HERE, "../../../.devcontainer-exclude/.env")
if (existsSync(ENV_FILE)) {
    for (const [key, value] of Object.entries(parseEnv(readFileSync(ENV_FILE, "utf8")))) {
        process.env[key] ??= value
    }
}

const toB64 = (bytes) => Buffer.from(bytes).toString("base64")

const writeArtifact = (payload) => {
    mkdirSync(dirname(OUT), { recursive: true })
    const body = `// Auto-generated by scripts/encrypt-token.mjs. Do not edit.\nexport default ${JSON.stringify(payload, null, 4)} as const\n`
    writeFileSync(OUT, body)
}

const empty = { ct: "", iv: "", salt: "", iter: 0 }

const token = process.env.ATN_TOKEN
const password = process.env.ATN_PASSWORD

if (!token || !password) {
    console.warn("[encrypt-token] ATN_TOKEN or ATN_PASSWORD not set — writing empty stub (dev fallback).")
    writeArtifact(empty)
    process.exit(0)
}

const salt = webcrypto.getRandomValues(new Uint8Array(16))
const iv = webcrypto.getRandomValues(new Uint8Array(12))

const baseKey = await webcrypto.subtle.importKey("raw", new TextEncoder().encode(password), { name: "PBKDF2" }, false, ["deriveKey"])

const key = await webcrypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITER, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
)

const ct = new Uint8Array(await webcrypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(token)))

writeArtifact({ ct: toB64(ct), iv: toB64(iv), salt: toB64(salt), iter: ITER })
console.log(`[encrypt-token] wrote ${OUT}`)
